### ISSUE TITLE
VABOrganizer Patch for Reflector Antennae not applied

### ISSUE THREAD

**Issue by coldrifting** [ChrisAdderley/NearFutureExploration#43]
All reflector antennae appear under the miscellaneous subcategory. Upon looking at the code, NF Exploration wants a subcategory called reflectors, but the subcategory name defined in the base VABOrganizer is just reflector. (No plural)

**Comment by ChrisAdderley** [comment]
I think you mentioned you've been using earlier verions of VABO. Check if you're updated to the latest, because that's not the case in latest: https://github.com/post-kerbin-mining-corporation/VABOrganizer/blob/1e892eb01ba7123f698e78609cb12ca37a86f558/GameData/VABOrganizer/Subcategories/communication.cfg#L18

**Comment by coldrifting** [comment]
Ah, you're totally right, my bad
